### PR TITLE
add Ground Projection sample (Plane variant)

### PR DESCRIPTION
**Pull request by kipash**
Rework of Ground Projection sample which includes a plane with animated propeller and a hangar panorama with the GroundProjectionEnv. 

- I've added a reflection probe to the scene to mimic the presence of the skybox, but it's not under the GLB Object, so it won't get exported. Do you think that is a good habit for samples to do?
- Made a short README for this sample which describes what the Ground Proj feature is. (package/Runtime/GroundProjection/README.md).

### CODE REVIEW

**Comment by marwie** [comment]
Thanks a lot! I'm looking into it now. Here are some smaller changes and things I noticed for the next time:

- Project Folder in samples should point ``Library/Needle/Sample`` if they dont contain any changes to the project template (usually the vite project). We consider projects in the `Library` temporary projects because they're usually ignored from git. Having a custom web project for each samples is a) slower to start because everything needs to installed the first time and b) add up to cost a lot of disc space when e.g. opening 10 samples and generating 10 projects.

  If the sample needs special changes it should go to `Packages/Web-Projects~/<SampleName>` (see e.g. the Scrollytelling sample)
  - Examples for when the project should go into `Packages/Web-Projects~/`:
    - the sample has custom code/HTML in e.g. the index.html or css files
    - the sample is using a special framework like vuejs
    - the sample has custom added code into `src/scripts` (usually that code should then go into a npmdef, see below)
  - Changes that don't require a custom project path:
    - the sample has a npmdef reference (added to the ExportInfo) - the ExportInfo component serializes those references and adds them to the package.json when generating the project from the template 

- Objects that are explictly editor only and only for editor visualization should be marked as `EditorOnly`, they then CAN go into the `GltfObject` hierarchy too but that's up to you I think.
  image 
  image

- Nice that you did the animation! I think i wouldnt make it change speeds so often tho - maybe just make it start slowly and speed up and spin for a while and then slow down again?

**Comment by kipash** [comment]
Thank you for the review.

> The sample MUST go into the Samples package (Packages/Needle Engine Samples/Runtime)
I'm afraid that i don't understand what you mean. I've really went through the folder structure multiple times and i'm just unsure what you mean by that.

Since, the sample is in `Needle Engine Samples/Packages/Runtime` and `Packages/Needle Engine Samples/Runtime` doesn't seem to exist? But i suppose you are not saying these things at random, so i'll need further explanation. I watched Felixe's talk, it explained the concept fully, which is nice. But haven't catch anything related to that note.

> Limiting OrbitControls max distance
Good point that it is super simple to go out of bounds. Didn't focused on that since all samples would deserve a constrained camera.

> The propeller anim
I definitely can change the anim to be less hectic. Although i feel a normal spinning won't be as interesting + without a blur.. it might look "cartoonish". Will iterate on that tomorrow.

**Comment by kipash** [comment]
Sorry, removed a lot of clutter which i wasn't aware that i had committed. So junior of me.

...

I'm bit puzzled with the structure. Since the `com.needle.engine-exporter` while generating the `samples.json` and `Samples.md` refers to `modules/` directory where it expects the samples to be.

But in this repo, the samples are present in root directly since this whole repository is the Package itself. So i suppose the provided UnityProject (`projects/Needle Engine Samples 2020_3`) is not for releasing / updating the samples (?) but just for validation / tests?

It seems that for the workflow to work, it has to have this structure:
```
/modules/needle-engine-samples
/???/UnityProj running exporter code (wd)
```

So then i figured the Unity Needle Engine Exporter could actually hint me something about the meaning of `modules/`, but i don't have access to that repo.

> The sample MUST go into the Samples package (Packages/Needle Engine Samples/Runtime)

Also i think this comment is tied to the structure as well and i don't understand it. So, i definitely need more explaining since i can't deduct what is the expected flow.

---

Although the samples work, if i add the package to some other UnityProj with needle engine, the newly added scene works.
But i can't generate the `samples.json` and `Samples.md` since the code expects the structure described above which i'm not sure how to fulfill. 

I can always edit the code and generate the files, discard the changes and commit the result.. but that doesn't seem like the way to go.

**Comment by marwie** [comment]
Up until now the samples package was managed from another repository where the Unity project was in a `projects` directory and this repository was in `modules`.
I think we should change that structure/dependency tho so that we can create and update samples using this repo only.

The next version of the Unity plugin has two changes related to that

- it will add a context menu to the SamplesCollection asset to hide/show the dev tools
  image

- I will also change the artifact path (samples.json) to not rely on outside structure

**Comment by hybridherbst** [comment]
>  added a reflection probe to the scene to mimic the presence of the skybox
Could you explain why that's needed?

**Pull request closed without merging**
